# Generated by Django 3.2.15 on 2022-10-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=10)),
                ('model_no', models.CharField(max_length=30)),
                ('operating_system', models.CharField(max_length=10)),
                ('processor_model', models.CharField(max_length=10)),
                ('processor_generation', models.CharField(max_length=5)),
            ],
        ),
    ]
