# Generated by Django 3.2.15 on 2022-10-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='disk_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='disk_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='picture_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='products',
            name='ram',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='screen_size',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='products',
            name='seller_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='model_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='model_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='operating_system',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='processor_generation',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='processor_model',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
