# Generated by Django 3.2.15 on 2022-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221015_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
