# Generated by Django 3.2.15 on 2022-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='model_no',
        ),
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
